use_frameworks!
source 'https://github.com/HLLComponent/LLSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'LLAPIsKit_Example' do
  pod 'LLAPIsKit', :path => '../'

  target 'LLAPIsKit_Tests' do
    inherit! :search_paths

    
  end
end
